In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sim_cp import run_i_n, random_generator
from sim import run_v2

* * *


In [ ]:
%%time

i, n = run_i_n(10 ** 8)

plt.plot(np.arange(len(i)), i)
plt.plot(np.arange(len(n)), n)

* * *


In [3]:
def pdf_to_cdf(pdf: np.array):
    cdf = pdf.copy()

    for ax in range(pdf.ndim):
        np.cumsum(cdf, axis=ax, out=cdf)
    return cdf

In [3]:
def equalize_length(a, b):
    len_a, len_b = len(a), len(b)
    max_len = max(len_a, len_b)

    out_a = np.zeros(max_len, dtype=a.dtype)
    out_b = np.zeros(max_len, dtype=b.dtype)

    out_a[:len_a] = a
    out_b[:len_b] = b

    return out_a, out_b

In [12]:
def diff(start = 5, end = 7, step = 1):
    times = [10 ** i for i in range(start, end, step)]

    table_len = len(times)

    d1 = np.zeros(table_len)
    d2 = np.zeros(table_len)

    for i in range(table_len):
        i1, n1 = run_i_n(times[i])
        i2, n2 = run_i_n(times[i])

        print(f'10^{start + i}', len(i1), len(i2), len(n1), len(n2))

        i1, i2 = equalize_length(i1, i2)
        n1, n2 = equalize_length(n1, n2)

        f11 = pdf_to_cdf(i1)
        f12 = pdf_to_cdf(n1)

        f21 = pdf_to_cdf(i2)
        f22 = pdf_to_cdf(n2)

        d1[i] = np.max(np.abs(f11 - f21))
        d2[i] = np.max(np.abs(f12 - f22))

    return pd.DataFrame({
        'D1': d1,
        'D2': d2
    }, index=[f'10^{i}' for i in range(start, end, step)])

In [13]:
diff().T

10^5 228 193 45 47
10^6 246 242 50 49


10^5      10^6
D1  0.072200  0.016899
D2  0.005531  0.003447

In [14]:
diff().T

10^5 229 202 45 47
10^6 252 255 49 49


10^5      10^6
D1  0.144709  0.018132
D2  0.015603  0.001866

In [15]:
diff(5, 9).T

10^5 202 218 46 44
10^6 234 251 46 46
10^7 255 274 55 50
10^8 280 295 56 54


10^5      10^6      10^7      10^8
D1  0.107160  0.020776  0.005368  0.002252
D2  0.014009  0.003466  0.001004  0.000376

In [81]:
diff(5, 9).T

10^5      10^6      10^7      10^8
D1  0.094531  0.035129  0.008459  0.002592
D2  0.002974  0.009185  0.001123  0.000282

In [ ]:
diff(10, 11).T

In [9]:
import torch

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print("MPS device not found.")

tensor([1.], device='mps:0')


In [2]:
!python -V

Python 3.13.5


In [11]:
random_generator()[:5], random_generator()[:5]

(array([0.31408383, 0.30238224, 0.66660812, 0.57848191, 0.55839583]),
 array([0.32993989, 2.11927994, 0.69355885, 0.07040188, 0.87553988]))