In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sim_cp import run_i_n
from multiprocessing import Pool

In [ ]:
[[None, None] for _ in range(it)]

In [48]:
diff().T

Process SpawnPoolWorker-19:
Process SpawnPoolWorker-18:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/pqp/miniconda3/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/Users/pqp/miniconda3/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pqp/miniconda3/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/Users/pqp/miniconda3/lib/python3.13/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/pqp/miniconda3/lib/python3.13/multiprocessing/queues.py", line 387, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/pqp/miniconda3/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^

KeyboardInterrupt: 

In [14]:
diff().T

10^5 229 202 45 47
10^6 252 255 49 49


10^5      10^6
D1  0.144709  0.018132
D2  0.015603  0.001866

In [33]:
diff(5, 9).T

10^5      10^6      10^7      10^8
D1  0.119703  0.008073  0.002787  0.001533
D2  0.023754  0.002812  0.000318  0.000768

In [81]:
diff(5, 9).T

10^5      10^6      10^7      10^8
D1  0.094531  0.035129  0.008459  0.002592
D2  0.002974  0.009185  0.001123  0.000282

In [ ]:
diff(10, 11).T

In [9]:
import torch

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print("MPS device not found.")

tensor([1.], device='mps:0')


In [2]:
!python -V

Python 3.13.5


In [ ]:
10 ** 6 

(array([0.31408383, 0.30238224, 0.66660812, 0.57848191, 0.55839583]),
 array([0.32993989, 2.11927994, 0.69355885, 0.07040188, 0.87553988]))

In [34]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])